server:
  port: 8084

spring:
  application:
    name: labels-service
  datasource:
    url: jdbc:sqlite:src/main/resources/db/database.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: com.javatar.labelsservice.config.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
